### ISSUE TITLE
NRE in Coresystems.Platform.LeadTarget

### ISSUE THREAD

**Issue by InvalidArgument3** [Ash-LikeSnow/WeaponCore#49]
## Is this a multiplayer or singleplayer bug?

both

## Steps To Reproduce:

appeared when fighting a bunch of random test NPCs in a world.

```
2024-05-29 03:04:40.657 - Thread:   1 ->  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Platform.Weapon.TrajectoryEstimation(Weapon weapon, Vector3D targetPos, Vector3D targetVel, Vector3D targetAcc, Vector3D shooterPos, Boolean& valid, Boolean basicPrediction, Boolean trackAngular)
   at CoreSystems.Platform.Weapon.LeadTarget(Weapon weapon, MyEntity target, Vector3D& targetPos, Boolean& couldHit, Boolean& willHit)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.ComputeLead(MyEntity target, Vector3D targetPos, Single& maxLeadLength, Vector3D& fullAveragePos)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawActiveLeads()
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawTargetUi()
   at CoreSystems.Session.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-05-29 03:04:40.660 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Platform.Weapon.TrajectoryEstimation(Weapon weapon, Vector3D targetPos, Vector3D targetVel, Vector3D targetAcc, Vector3D shooterPos, Boolean& valid, Boolean basicPrediction, Boolean trackAngular)
   at CoreSystems.Platform.Weapon.LeadTarget(Weapon weapon, MyEntity target, Vector3D& targetPos, Boolean& couldHit, Boolean& willHit)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.ComputeLead(MyEntity target, Vector3D targetPos, Single& maxLeadLength, Vector3D& fullAveragePos)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawActiveLeads()
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawTargetUi()
   at CoreSystems.Session.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-05-29 03:04:40.660 - Thread:   1 ->  Showing message
2024-05-29 03:04:40.660 - Thread:   1 ->  MyInitializer.OnCrash
2024-05-29 03:04:40.660 - Thread:   1 ->  var exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreSystems.Platform.Weapon.TrajectoryEstimation(Weapon weapon, Vector3D targetPos, Vector3D targetVel, Vector3D targetAcc, Vector3D shooterPos, Boolean& valid, Boolean basicPrediction, Boolean trackAngular)
   at CoreSystems.Platform.Weapon.LeadTarget(Weapon weapon, MyEntity target, Vector3D& targetPos, Boolean& couldHit, Boolean& willHit)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.ComputeLead(MyEntity target, Vector3D targetPos, Single& maxLeadLength, Vector3D& fullAveragePos)
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawActiveLeads()
   at WeaponCore.Data.Scripts.CoreSystems.Ui.Targeting.TargetUi.DrawTargetUi()
   at CoreSystems.Session.Draw()
   at Sandbox.Game.World.MySession.DrawSync()
   at Sandbox.Game.Gui.MyGuiScreenGamePlay.Draw()
   at Sandbox.Graphics.GUI.MyScreenManager.DrawScreens(MyGuiScreenBase screenFade)
   at Sandbox.Graphics.GUI.MyScreenManager.Draw()
   at Sandbox.Graphics.GUI.MyDX9Gui.Draw()
   at Sandbox.Graphics.GUI.MyGuiSandbox.Draw()
   at Sandbox.MySandboxGame.PrepareForDraw()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
   ```

**Comment by BDCarrillo** [comment]
Closing as intermittent and not reproducible
